#!/usr/bin/perl

use strict;
use warnings;
use utf8;

our @CustomFields = ();
push @CustomFields, {
	LookupType  => 'RT::Queue-RT::Ticket',
	Pattern  => '',
	Disabled  => '0',
	Name  => 'TextJegyzet',
	MaxValues  => '1',
	Description  => '',
	EntryHint  => 'Egy szöveges mező kitöltése',
	UniqueValues  => '0',
	Type  => 'Text',
	ApplyTo => [ 'Lista: Alapdokumentum' ] ,
};
push @CustomFields, {
	EntryHint => 'Szabad értékmegadás (egy)',
	Description => '',
	UniqueValues => '0',
	Name => 'Q-FolderStruktura',
	Type => 'Freeform',
	LookupType => 'RT::Queue',
	MaxValues => '1',
	Disabled => '0',
	Pattern => '',
};
our @Queues = ();
push @Queues, {
	Name  => 'Lista: Alapdokumentum',
	Description  => '',
	SubjectTag  => '',
	SortOrder  => '0',
	Disabled  => '0',
};
our @ACL = ();


1;