#!/usr/bin/perl

use strict;
use warnings;
use utf8;

our @Queues = ();
push @Queues, {
	Name  => 'Lista: Alapdokumentum',
	Description  => 'Alapdokumentumok',
	SubjectTag  => '',
	SortOrder  => '0',
	Disabled  => '0',
};

our @CustomFields = ();
push @CustomFields, {
	LookupType  => 'RT::Queue-RT::Ticket',
	Pattern  => '',
	Disabled  => '0',
	Name  => 'TextJegyzet',
	MaxValues  => '1',
	Description  => 'Text jegyzet;BigBox',
	EntryHint  => 'Egy szöveges mező kitöltése',
	UniqueValues  => '0',
	Type  => 'Text',
	ApplyTo => [ 'Lista: Alapdokumentum' ] ,
};

our @Final = (sub {
	print "Create ticket...\n";
	my $ticket = RT::Ticket->new( RT->SystemUser );
	my %args = (
		Queue=>"Lista: Alapdokumentum",
		Subject=>"Általános kategóriák", 
		Priority=>10,
		InitialPriority=>0,
		FinalPriority=>0,
		Owner=>'robot',
	);
	my $cf = RT::CustomField->new( RT->SystemUser );
	$cf->Load('TextJegyzet');
	$args{ 'CustomField-' . $cf->id } = "1;9999;Általános";
	my ($ret, $msg) = $ticket->Create( %args );
	printf ("Ticket #%d created\n", $ret) if ($ret);
	die $msg unless $ret;
});

our @ACL = ();

1;
